apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
#- "git@github.com:kubernetes-sigs/kustomize/examples/helloWorld"
#- github.com/kubernetes-sigs/kustomize/examples/helloWorld?ref=HEAD
#- https://github.com/kubernetes-sigs/kustomize/tree/master/examples/helloWorld
- github.com/kubernetes-sigs/kustomize/examples/helloWorld?ref=HEAD

- name: test
  git:
    repo: https://github.com/kubernetes-sigs/kustomize.git
    ref: main
    directory: examples/ldap/overlays/staging
namePrefix: dev-
nameSuffix: "-001"
commonLabels:
  app: bingo
commonAnnotations:
  oncallPager: 800-555-1212
